In [51]:
import numpy as np
import CDPL.Chem as Chem
import CDPL.Biomol as Biomol
import CDPL.Math as Math
import CDPL.Pharm as Pharm
import CDPL.Base as Base
import CDPL.Shape as Shape
import sys
sys.path.append('../utils')
from Protein import Protein
from ProteinTools import THREE_LETTER_AMINO_ACID_CODES
from scipy.spatial.transform import Rotation

In [2]:
path = '../Data/benchmark5.5/structures/'

In [3]:
p = Protein()
p.fromFile('{}1A2K_l_b.pdb'.format(path))

In [4]:
p.numAtoms

1598

In [5]:
# remove ligands and other crystalization artifacts
p.separateLigandFromProtein()

[1570]
[1571]
[1572]
[1573]
[1574]
[1575]
[1576]
[1577]
[1578]
[1579]
[1580]
[1581]
[1582]
[1583]
[1584]
[1585]
[1586]
[1587]
[1588]
[1589]
[1590]
[1591]
[1592]
[1593]
[1594]
[1595]
[1596]
[1597]


In [6]:
p.numAtoms

1570

In [7]:
p.ligands

In [12]:
p.getGaussianShape()

In [29]:
shape, shapeFunc = p.shape, p.shapeFunc

In [30]:
contributingAtoms = []
for i in range(p.numAtoms): 
    atom = p.getAtom(i)
    surfAreaContr = shapeFunc.calcSurfaceArea(i)
    # print(i, Chem.getType(atom), surfAreaContr)
    if surfAreaContr > 0: 
        print(i, Chem.getType(atom), surfAreaContr)
        contributingAtoms.append(atom)
        
len(contributingAtoms)

0 7 30.190705400997917
1 6 36.316811075497995
2 6 36.316811075497995
3 8 29.033342667415432
4 6 36.316811075497995
5 6 36.316811075497995
6 6 36.316811075497995
7 8 29.033342667415432
8 7 30.190705400997917
9 7 30.190705400997917
10 6 36.316811075497995
11 6 36.316811075497995
12 8 29.033342667415432
13 6 36.316811075497995
14 6 36.316811075497995
15 6 36.316811075497995
16 7 30.190705400997917
17 6 36.316811075497995
18 6 36.316811075497995
19 8 29.033342667415432
20 6 36.316811075497995
21 6 36.316811075497995
22 6 36.316811075497995
23 8 29.033342667415432
24 7 30.190705400997917
25 7 30.190705400997917
26 6 36.316811075497995
27 6 36.316811075497995
28 8 29.033342667415432
29 6 36.316811075497995
30 6 36.316811075497995
31 6 36.316811075497995
32 6 36.316811075497995
33 6 36.316811075497995
34 6 36.316811075497995
35 6 36.316811075497995
36 7 30.190705400997917
37 6 36.316811075497995
38 6 36.316811075497995
39 8 29.033342667415432
40 6 36.316811075497995
41 6 36.316811075497995
42

1570

In [31]:
shapeFunc.distCutoff

0.0

In [32]:
shapeFunc.setDistanceCutoff(1)

In [33]:
contributingAtoms = []
for i in range(p.numAtoms): 
    atom = p.getAtom(i)
    surfAreaContr = shapeFunc.calcSurfaceArea(i)
    # print(i, Chem.getType(atom), surfAreaContr)
    if surfAreaContr > 0: 
        print(i, Chem.getType(atom), surfAreaContr)
        contributingAtoms.append(atom)
        
len(contributingAtoms)

0 7 30.190705400997917
1 6 36.316811075497995
2 6 36.316811075497995
3 8 29.033342667415432
4 6 36.316811075497995
5 6 36.316811075497995
6 6 36.316811075497995
7 8 29.033342667415432
8 7 30.190705400997917
9 7 30.190705400997917
10 6 36.316811075497995
11 6 36.316811075497995
12 8 29.033342667415432
13 6 36.316811075497995
14 6 36.316811075497995
15 6 36.316811075497995
16 7 30.190705400997917
17 6 36.316811075497995
18 6 36.316811075497995
19 8 29.033342667415432
20 6 36.316811075497995
21 6 36.316811075497995
22 6 36.316811075497995
23 8 29.033342667415432
24 7 30.190705400997917
25 7 30.190705400997917
26 6 36.316811075497995
27 6 36.316811075497995
28 8 29.033342667415432
29 6 36.316811075497995
30 6 36.316811075497995
31 6 36.316811075497995
32 6 36.316811075497995
33 6 36.316811075497995
34 6 36.316811075497995
35 6 36.316811075497995
36 7 30.190705400997917
37 6 36.316811075497995
38 6 36.316811075497995
39 8 29.033342667415432
40 6 36.316811075497995
41 6 36.316811075497995
42

1570

In [34]:
shapeFunc.surfaceArea

53387.937785219416

In [35]:
totalSA = 0
for i in range(p.numAtoms): 
    atom = p.getAtom(i)
    surfAreaContr = shapeFunc.calcSurfaceArea(i)
    # print(i, Chem.getType(atom), surfAreaContr)
    totalSA += surfAreaContr
    
totalSA

53387.937785219416

In [46]:
coords = Math.Vector3DArray()

In [37]:
coords

In [38]:
coords.getSize()

0

In [39]:
coords.assign()

ValueError: VectorArray: NumPy.NDArray dimension error

In [48]:
Chem.get3DCoordinates(p, coords)

In [43]:
coords.getSize()

1570

In [44]:
coords.getCapacity()

2048

In [47]:
coords.isEmpty()

True

In [49]:
coords.toArray(True)

array([ 69.129,  20.057,  76.586, ...,  64.984, -13.617,  57.14 ])

In [50]:
coords.toArray(False)

array([[ 69.129,  20.057,  76.586],
       [ 69.043,  18.629,  76.973],
       [ 68.04 ,  17.937,  76.052],
       ...,
       [ 68.097, -11.364,  57.364],
       [ 65.909, -13.525,  58.34 ],
       [ 64.984, -13.617,  57.14 ]])

In [52]:
r = Rotation.random().as_matrix()
r

array([[-0.97366621, -0.06655923, -0.21804581],
       [ 0.19086355,  0.28508146, -0.93930808],
       [ 0.12468044, -0.95618954, -0.26487045]])

In [59]:
rotMatrix = Math.Matrix3D()

In [54]:
rotMatrix.getSize1(), rotMatrix.getSize2()

(3, 3)

In [56]:
rotMatrix.toArray()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
for i in range(r.shape[0]): 
    for j in range(r.shape[1]): 
        rotMatrix[i, j] = r[i, j]
        
rotMatrix.toArray()

array([[-0.97366621, -0.06655923, -0.21804581],
       [ 0.19086355,  0.28508146, -0.93930808],
       [ 0.12468044, -0.95618954, -0.26487045]])

In [60]:
rotMatrix.assign(r)

In [61]:
rotMatrix.toArray()

array([[-0.97366621, -0.06655923, -0.21804581],
       [ 0.19086355,  0.28508146, -0.93930808],
       [ 0.12468044, -0.95618954, -0.26487045]])

In [66]:
coords.assign(rotMatrix.toArray()*coords.toArray(False))
coords.toArray(False)

ValueError: operands could not be broadcast together with shapes (3,3) (1570,3) 

In [67]:
np.matmul(coords.toArray(False), rotMatrix.toArray())

array([[-53.93164555, -72.11402606, -54.19835919],
       [-54.07221207, -72.88544364, -52.94078018],
       [-53.34253311, -72.13531054, -51.82813336],
       ...,
       [-61.32055284, -62.62300613, -19.36799688],
       [-59.48093918, -64.02667656, -17.11958146],
       [-58.7474739 , -62.84390932, -16.5136282 ]])

In [64]:
direction = Math.Vector3D()
for i in range(3): 
    direction[i] = i
    
direction.toArray()

array([0., 1., 2.])

In [68]:
coords.toArray(False)+direction

array([[ 69.129,  21.057,  78.586],
       [ 69.043,  19.629,  78.973],
       [ 68.04 ,  18.937,  78.052],
       ...,
       [ 68.097, -10.364,  59.364],
       [ 65.909, -12.525,  60.34 ],
       [ 64.984, -12.617,  59.14 ]])

In [69]:
np.random.randn(3)

array([ 0.73516816,  1.72640521, -0.33480521])

In [71]:
direction.assign([1, 2, 3])

In [72]:
direction.toArray()

array([1., 2., 3.])

In [74]:
direction.assign(np.random.rand(3)*10)

In [75]:
direction.toArray()

array([1.11686962, 6.84605011, 3.80421737])

In [76]:
a = p.getAtom(0)

In [77]:
Chem.getType(a)

7

In [78]:
Chem.getSymbol(a)

'N'